name: Build iOS

on: [push]

jobs:
  build:
    name: Build iOS Example App
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: example/ios
    steps:
      - uses: actions/checkout@v3
      # build opaque_rust lib
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23b
      - name: Add iOS targets
        working-directory: rust
        run: rustup target add x86_64-apple-ios aarch64-apple-ios aarch64-apple-ios-sim
      - name: Add Android targets
        working-directory: rust
        run: rustup target add i686-linux-android x86_64-linux-android aarch64-linux-android arm-linux-androideabi
      - name: Install cxxbridge
        working-directory: rust
        run: cargo install cxxbridge-cmd
      - name: build
        working-directory: rust
        run: ./build-all.sh
        env:
          NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
      # build iOS app
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules for example/
        run: yarn install --frozen-lockfile --cwd ..
      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v1
        continue-on-error: true
      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
          working-directory: example/ios
      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            example/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      # fix for ruby https://github.com/facebook/react-native/issues/37301#issuecomment-1540484759
      - name: Fix for ruby
        run: |
          bundle config --local build.ffi --with-cflags=-Wno-error=implicit-function-declaration
          bundle install
      - name: Install Pods
        run: bundle exec pod check || bundle exec pod install
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build App
        run: "set -o pipefail && xcodebuild \
          CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace OpaqueExample.xcworkspace \
          -scheme OpaqueExample \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 11' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty"
