name: Web e2e tests

on: [push]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yarn
        run: yarn --frozen-lockfile
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: yarn test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
